CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TYPE RELATION_STATUS AS ENUM ('follow');
CREATE TABLE USERS(
    USER_ID uuid DEFAULT uuid_generate_v1(),
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100),
    EMAIL VARCHAR(200) UNIQUE NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    CREATED_AT DATE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(USER_ID)
);
CREATE TABLE ACCOUNTS(
    ACCOUNT_ID uuid DEFAULT uuid_generate_v1(),
    ACCOUNT_NAME VARCHAR(100) NOT NULL,
    DOB DATE NOT NULL,
    ADDRESS TEXT,
    DESCRIPTION TEXT,
    CREATED_AT DATE DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY UUID NOT NULL,
    PRIMARY KEY(ACCOUNT_ID),
    CONSTRAINT CREATED_BY FOREIGN KEY(CREATED_BY) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);
CREATE TABLE RELATIONS(
    OBSERVER_ID UUID REFERENCES ACCOUNTS(ACCOUNT_ID) ON DELETE CASCADE,
    OBSERVED_ID UUID REFERENCES ACCOUNTS(ACCOUNT_ID) ON DELETE CASCADE,
    STATUS RELATION_STATUS NOT NULL,
    PRIMARY KEY(OBSERVED_ID, OBSERVER_ID)
);