// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (uuid.UUID, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, arg DeleteAccountParams) error
	FindUser(ctx context.Context, lower string) (FindUserRow, error)
	ReadAccount(ctx context.Context, arg ReadAccountParams) (ReadAccountRow, error)
	ReadAllAccount(ctx context.Context, arg ReadAllAccountParams) ([]ReadAllAccountRow, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
