// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: users.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO USERS (FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) VALUES($1,$2,$3,$4) RETURNING user_id, first_name, last_name, email, password, created_at, updated_at
`

type CreateUserParams struct {
	FirstName string         `json:"first_name"`
	LastName  sql.NullString `json:"last_name"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Password,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUser = `-- name: FindUser :one
SELECT USER_ID, EMAIL, PASSWORD FROM USERS WHERE LOWER(EMAIL) = LOWER($1) LIMIT 1
`

type FindUserRow struct {
	UserID   uuid.UUID `json:"user_id"`
	Email    string    `json:"email"`
	Password string    `json:"password"`
}

func (q *Queries) FindUser(ctx context.Context, lower string) (FindUserRow, error) {
	row := q.db.QueryRowContext(ctx, findUser, lower)
	var i FindUserRow
	err := row.Scan(&i.UserID, &i.Email, &i.Password)
	return i, err
}
