-- name: CreateAccount :one
INSERT INTO ACCOUNTS (ACCOUNT_NAME, DOB, ADDRESS, DESCRIPTION, CREATED_BY) VALUES ($1,$2,$3,$4,$5) RETURNING ACCOUNT_ID;

-- name: ReadAccount :one
SELECT ACCOUNT_ID, ACCOUNT_NAME, DOB, ADDRESS, DESCRIPTION, CREATED_AT FROM ACCOUNTS 
WHERE ACCOUNT_ID = $1 AND CREATED_BY = $2 AND STATUS = 'active';

-- name: ReadAllAccount :many
SELECT ACCOUNT_ID, ACCOUNT_NAME, DOB, ADDRESS, DESCRIPTION, CREATED_AT FROM ACCOUNTS 
WHERE CREATED_BY = $1 OFFSET $2 LIMIT $3;

-- name: UpdateAccount :one
UPDATE ACCOUNTS SET ACCOUNT_NAME = $1, DOB = $2, ADDRESS = $3, DESCRIPTION = $4 WHERE ACCOUNT_ID = $5 AND CREATED_BY = $6 RETURNING ACCOUNT_ID;

-- name: DeleteAccount :exec
UPDATE ACCOUNTS SET STATUS = 'unactive' WHERE ACCOUNT_ID = $1 AND CREATED_BY = $2;