-- name: CreateUser :one
INSERT INTO USERS (FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) VALUES($1,$2,$3,$4) RETURNING *;

-- name: FindUser :one
SELECT USER_ID, EMAIL, PASSWORD FROM USERS WHERE LOWER(EMAIL) = LOWER($1) LIMIT 1;